name: Test Suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        fail-fast: false
        app: [client, server]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ${{ matrix.app }}/package-lock.json

    - name: Install Dependencies
      working-directory: ./${{ matrix.app }}
      run: npm ci

    - name: Run Tests
      working-directory: ./${{ matrix.app }}
      run: npm test
      env:
        CI: true
        NODE_ENV: test 